// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACADxABeQgqZY6CVcoN-IeOs-JYcMU6sk',
    appId: '1:347912771449:web:d8532e444db186bdcc41a8',
    messagingSenderId: '347912771449',
    projectId: 'sos-cttu',
    authDomain: 'sos-cttu.firebaseapp.com',
    storageBucket: 'sos-cttu.firebasestorage.app',
    measurementId: 'G-LRDVK33JCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZbCk-jLcSKBAZXz2sZuaWeX_6XP6Tybo',
    appId: '1:347912771449:android:3242589c91fa30e8cc41a8',
    messagingSenderId: '347912771449',
    projectId: 'sos-cttu',
    storageBucket: 'sos-cttu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVaMjhfamp5VnB9k4-qgihEoUD2RN0HeQ',
    appId: '1:347912771449:ios:ac49c6f4dc273c9acc41a8',
    messagingSenderId: '347912771449',
    projectId: 'sos-cttu',
    storageBucket: 'sos-cttu.firebasestorage.app',
    iosBundleId: 'com.example.sosCttu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVaMjhfamp5VnB9k4-qgihEoUD2RN0HeQ',
    appId: '1:347912771449:ios:ac49c6f4dc273c9acc41a8',
    messagingSenderId: '347912771449',
    projectId: 'sos-cttu',
    storageBucket: 'sos-cttu.firebasestorage.app',
    iosBundleId: 'com.example.sosCttu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACADxABeQgqZY6CVcoN-IeOs-JYcMU6sk',
    appId: '1:347912771449:web:7cdcb93e07e2d732cc41a8',
    messagingSenderId: '347912771449',
    projectId: 'sos-cttu',
    authDomain: 'sos-cttu.firebaseapp.com',
    storageBucket: 'sos-cttu.firebasestorage.app',
    measurementId: 'G-LHYZ6SYDS4',
  );

}